---
title: Web server in Kubernetes
description: Not so simple grading example for Kubernetes
instructions: |
    <p>
        In this exercise you must start web server in Kubernetes with custom content using ConfigMap.
    </p>
    <p>
        You must use an NGINX image for this task and the name of the deployment must be "nginx-deployment".
        The server must run in the port 80 and the port must be exposed by a service named "nginx-service".
        Succeeding in this, will grant you 5 out of 10 points.
        (Hint: Type of the service must be NodePort.)
    </p>
    <p>
        To receive full points, the web server must also reply with custom content and not just with the
        NGINX's default start page. The custom page must contain the text "Hei, Kubernetes!" (without 
        the quotes) and you must use Kubernetes ConfigMap in this task.
        (Hint: The config map should be mounted to the nginx-deployment.)
    </p>
    <p>
        Add all the required services and configurations to one Kubernetes YAML-config file and submit it
        below. You can separate services in a single file by adding a line containing 3 dashes in between
        the components (---).
    </p>
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: submission.yaml

container:
  image: k8s-grader
  mount: exercises/k8s
  cmd: /exercise/run.sh ex1
