---
title: PersistentVolumes in Kubernetes
description: Not so simple grading example for Kubernetes
instructions: |
    <p>
        In this exercise you must start web server in Kubernetes with custom content using PersistentVolume.
    </p>
    <p>
        You must use an NGINX image for this task and the name of the deployment must be "nginx-deployment".
        The server must run in the port 80 and the port must be exposed by a service named "nginx-service".
        Succeeding in this, will grant you 5 out of 10 points.
        (Hint: Type of the service must be NodePort.)
    </p>
    <p>
        To receive full points, the web server must also reply with custom content and not just with the
        NGINX's default start page. The custom page must contain the text "Persistence!" (without 
        the quotes) and you must use Kubernetes PersistentVolume and PersistentVolumeClaim in this task.
        (Hint: The persistent volume claim should be a volume of the nginx-deployment.)
    </p>
    <p>
      The custom content must be submitted as a separate HTML-file below. The file will be copied to
      destination cluster's "/mnt/data" directory. Use this in your PersistentVolume configuration.
      (Hint: PersistentVolume is "local" and the directory is a "hostPath". Size should not exceed 1Gi.)
    </p>
    <p>
        Add all the required services and configurations to one Kubernetes YAML-config file and submit it
        below. You can separate services in a single file by adding a line containing 3 dashes in between
        the components (---).
    </p>
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: submission.yaml
  - field: file2
    name: index.html

container:
  image: k8s-grader
  mount: exercises/k8s
  cmd: /exercise/run.sh ex2
